export default {
    darkMode: ["class"],
    content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        extend: {
            colors: {
                background: "hsl(0 0% 100%)",
                foreground: "hsl(0 0% 3.6%)",
                card: "hsl(0 0% 100%)",
                "card-foreground": "hsl(0 0% 3.6%)",
                popover: "hsl(0 0% 100%)",
                "popover-foreground": "hsl(0 0% 3.6%)",
                muted: "hsl(0 0% 96.1%)",
                "muted-foreground": "hsl(0 0% 45.1%)",
                accent: "hsl(0 0% 9.0%)",
                "accent-foreground": "hsl(0 0% 100%)",
                destructive: "hsl(0 84.2% 60.2%)",
                "destructive-foreground": "hsl(0 0% 100%)",
                border: "hsl(0 0% 89.8%)",
                input: "hsl(0 0% 89.8%)",
                ring: "hsl(0 0% 3.6%)",
                primary: "hsl(0 0% 9.0%)",
                "primary-foreground": "hsl(0 0% 100%)",
                secondary: "hsl(0 0% 96.1%)",
                "secondary-foreground": "hsl(0 0% 9.0%)",
                "chart-1": "hsl(12 76% 61%)",
                "chart-2": "hsl(173 58% 39%)",
                "chart-3": "hsl(197 37% 24%)",
                "chart-4": "hsl(43 74% 66%)",
                "chart-5": "hsl(27 87% 67%)",
            },
            borderRadius: {
                lg: "0.5rem",
                md: "calc(0.5rem - 2px)",
                sm: "calc(0.5rem - 4px)",
            },
        },
    },
    plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
};
